name: Unit test

on: [push]

env:
  SPANNER_EMULATOR_HOST: localhost:9010
  SPANNER_PROJECT_ID: alertchain-test
  SPANNER_INSTANCE_ID: test-instance
  SPANNER_DATABASE_ID: test-db
  WRENCH_VERSION: v1.0.4

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout upstream repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - uses: google-github-actions/setup-gcloud@v0.5.0
      - run: go test ./pkg/...
